### ISSUE TITLE
Audit report is not conform with new security-report schema

### ISSUE THREAD

**Issue by Soufian20** [dcoles/gitlab-cargo-audit#3]
We are using a Gitlab Enterprise Edition v16.8.1-ee instance and viewing the audit report is not possible in Gitlab.
Looks like the report is not anymore conform with the JSON schema -> https://gitlab.com/gitlab-org/security-products/security-report-schemas/-/blob/master/dist/dependency-scanning-report-format.json

So the UI shows:
![grafik](https://github.com/dcoles/gitlab-cargo-audit/assets/38558643/f61f6b7f-c30f-41b8-a6bc-e838272e0b3d)

Any chance to update the report version and add the missing required key?

**Comment by dcoles** [comment]
Hi @Soufian20,

Sorry for the delayed response. I'd missed this one when it came in. I suspect that our own GitLab EE pipeline might also be broken due to the incompatible schema changes. I'll take a look this week.

I see @roblabla has already started #5 to update to the 15.0.7 schema, which is greatly appreciated. Would be very happy to accept this when they feel it's ready to merge.
