### ISSUE TITLE
Pipe output on Windows machines is UTF-16, cannot be consumed by GitLab

### ISSUE THREAD

**Issue by NuSkooler** [dcoles/gitlab-cargo-audit#8]
Piping output on at least some Windows machines produces a UTF-16 output which cannot be consumed by GitLab.

**Comment by NuSkooler** [comment]
A possible fix: If it's not a tty, just force UTF-8 output

**Comment by dcoles** [comment]
Hi @NuSkooler. Thanks for the bug report.

I think I agree with you that the easiest approach would be just to force the output to UTF-8 or even just ASCII. Since it's almost all JSON encoded, we don't have to worry about un-encoded Unicode characters.

**Comment by NuSkooler** [comment]
@dcoles I'm happy to submit a PR if that sounds reasonable to you!

**Comment by dcoles** [comment]
> @dcoles I'm happy to submit a PR if that sounds reasonable to you!

Sounds good! Thanks for that!

**Comment by dcoles** [comment]
I took a closer look into this, and it appears that [PowerShell is the cause of UTF-16 being written when using `>` redirection](https://stackoverflow.com/a/40098904/1172350) (an alias for [`Out-File`](https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.utility/out-file?view=powershell-5.1)).

Under `cmd.exe` `>` gives me valid UTF-8 output, but I get UTF-16 LE under PowerShell 5.1. If I switch to `... | Out-File output.txt -Encoding oem` then I get the same results as `cmd.exe`.

(Note: There's something funny going on between Rust and PowerShell and UTF-16, since printing a emoji character produces corrupted output.

So I still think @NuSkooler suggestion of an explicit `--output-path` argument is the best way to avoid the whole mess.

**Comment by NuSkooler** [comment]
Thanks again @dcoles. The one thing I didn't yet do in that MR is get the `README.md` updated. Otherwise, it's working on all versions of Windows now!

**Comment by dcoles** [comment]
Ah, thanks for the reminder. I'll add a comment to the usage instructions.

Glad to hear it's working well! Thanks for the PR!
